# service/category_service.py

from dao.category_dao import CategoryDAO
from model.category import Category

class CategoryService:
    def __init__(self):
        # Instantiate the DAO so we can call its methods
        self.category_dao = CategoryDAO()

    def list_categories(self):
        """
        Fetch all categories from the DAO.
        """
        return self.category_dao.list_all()

    def add_category(self, name):
        """
        Create a Category object and send it to the DAO to be inserted into the DB.
        """
        new_category = Category(None, name) 
        # None is used because 'id' will be generated by SERIAL in PostgreSQL
        
        self.category_dao.create(new_category)
        # Optionally return the newly created category if you'd like
        return new_category

    def delete_category(self, category_id):
        """
        Call the DAO to delete the category by ID.
        """
        self.category_dao.delete(category_id)

    def get_category_by_id(self, category_id):
        """
        Fetch a single category by ID through the DAO.
        """
        return self.category_dao.find_by_id(category_id)
